# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
    adapter: postgresql
    encoding: unicode
    username: recall
    password:
    pool: 5

development:
    <<: *common
    database: recall_dev

test:
    <<: *common
    database: recall_test

production:
    <<: *common
    database: recall_prod
